/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Authenticated API Example
 * An example API which uses bearer token scopes and JWT auth
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
export type GetToken200 = {
  token?: string;
};

export type GetTokenBody = {
  password: string;
  username: string;
};

export interface Error {
  /** Error code */
  code: number;
  /** Error message */
  message: string;
}

export type EventsWithIDAllOf = {
  id: number;
};

export interface Events {
  description: string;
  imageUrl?: string;
  name: string;
}

export type EventsWithID = Events & EventsWithIDAllOf;





  /**
 * Returns a JWT token for a given username and password. This endpoint
does not require a JWT token to access.

 */
export const getToken = <TData = AxiosResponse<GetToken200>>(
    getTokenBody: GetTokenBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/auth/token`,
      getTokenBody,options
    );
  }

/**
 * Returns a list of events. This endpoint requires a JWT token with the
`read:events` scope to access.

 */
export const listEvents = <TData = AxiosResponse<EventsWithID[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/events`,options
    );
  }

export type GetTokenResult = AxiosResponse<GetToken200>
export type ListEventsResult = AxiosResponse<EventsWithID[]>
